
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace appUrbanTransport.BD
{

using System;
    using System.Collections.Generic;
    
public partial class Routes
{

    public int id_route { get; set; }

    public int id_transport { get; set; }

    public int number_of_cars { get; set; }

    public float price { get; set; }

    public int number_of_passengers { get; set; }

    public string route_start { get; set; }

    public string route_end { get; set; }



    public virtual Transport Transport { get; set; }

}

}
